- name: file variables
  hosts: local
  connection: local

  vars_files:
  - course.yaml
  tasks:
   - name: print file variables
     ansible.builtin.debug:
       msg: "course is : {{course}}"

    
