- name: demo on loops
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: loops program
      ansible.builtin.packages:
       name: "{{item}}"
       state: present
      loop:
       - linux
       - mysql
       - json 
